### ISSUE TITLE
Bestiary No longer accessible after latest update

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#52]
Updated this morning and now I can no longer open the bestiary. 

Tried both hot key and side bar.

**Comment by fishrobe** [comment]
Might have something to do with this error 
![bestiary error](https://github.com/user-attachments/assets/bcb4fa5d-9c37-492d-8732-224a814fed7d)

**Comment by WBHarry** [comment]
This is very confusing to me. You've essentially downloaded a Test version I never added to Foundry. 🫨

**Comment by WBHarry** [comment]
This was...a very silly error that's very frustrating to me. The downloads were pointing to 'Latest Version', which was a work in progress test.

I've released 0.8.9 now, which points where it should. It should fix this hopefully! 😓

**Comment by ThomaSutra** [comment]
I have never gotten the above error message. Until yesterday, everything was working fine. 

Just did an additional update 5 minutes ago, Problem continues to persist. 

Cannot open bestiary by any means. Not by side bar or either of the 2 short cut macros

**Comment by ThomaSutra** [comment]
> This was...a very silly error that's very frustrating to me. The downloads were pointing to 'Latest Version', which was a work in progress test.
> 
> I've released 0.8.9 now, which points where it should. It should fix this hopefully! 😓

Nope. Still can't get it to work. Should I uninstall and try again? I'd hate to lose the work I've put into it, but If I have to I will.

**Comment by Khybersghost** [comment]
+1 for the bestiary no longer opening after I updated today. Console error below. 
![image](https://github.com/user-attachments/assets/9a4fd433-760d-46c8-9593-04066734fee2)

**Comment by WBHarry** [comment]
Alrighty. I pushed out v0.8.9.1 after testing on the world of another user that was stuck, and I got it working.
Give it a try and tell me how it went. 🧑‍🔧

**Comment by ThomaSutra** [comment]
That did it. Full access.

However, there is a new issue...opened in a new thread

BTW, Thank you for all the work you are putting into the awesome Mod. 

I hope Pazio incorporates it into the base game

**Comment by fishrobe** [comment]
Still can't open it after the latest update, thouogh the other two macros seem to work fine (I get the normal notices about it, anyway, but I can't open it to see if anything was really added). I get this in the console.
![beast tracking](https://github.com/user-attachments/assets/09b3875b-2ee7-45d1-94e4-fef7895d7da8)

**Comment by WBHarry** [comment]
@fishrobe I'm pretty sure your world has gotten stuck in migration because one of the monsters you've added has some quirks to it that I haven't run into before.

Only real way for me to figure it out would be if you could send me a zip of the world where this errors happens on discord, so that I can see it and fix it 🧑‍🔧

**Comment by fishrobe** [comment]
Hmm ok. Oddly when I got home to check today it wasn't installed at all
(wasn't even in my module list) but when I re-added it, I got this error.
How can I send you a zip of the world? (I have several worlds--I haven't
had a chance to check whether this is happening with all of them or not. I
am away from my PC now but I will check it ASAP).

Is there any way I can unstick the migration?

**Comment by WBHarry** [comment]
Easiest way to send it would probably be to zip it up and add it to your google drive and give me a link.
Unsticking the migration - IE making it go through, is what I'd be looking to do by seeing what's going wrong 😛 

It's always possible to easily reset the Bestiary which will remove problems, but losing data isn't fun - and it could also help others if I can see what the issue is.

**Comment by fishrobe** [comment]
Hmm ok. I am on Molten but I can download my game data and send you the
link. I'd rather not just post it here, though. Is there somewhere else I
can send it? I didn't have very many monsters set up so I'm not worried
about losing anything, if there's a way to fix it myself (apparently
uninstalling the module won't work since it uninstalled itself somehow
already).

**Comment by WBHarry** [comment]
Sure, if you don't mind losing the data you just have to run this command in the console, or as a macro once.
```
game.settings.set('pf2e-bestiary-tracking', 'bestiary-tracking', { monster: {}, npc: {} });
```

**Comment by fishrobe** [comment]
Ok I'll give it a shot. I did try to delete it and reinstall it. It works
fine in one world (didn't even lose any monsters) but in the other one it
still won't open. I'll try this and let you know!

**Comment by WBHarry** [comment]
Yeah, just removing the module doesn't do anything since the settings are still there.

Sorry it became a continous issue - but with 0.8.9 out, these issues shouldn't ever crop up again 👍
